version: 2

jobs:
  11-linux:
    docker:
      - image: vapor/swift:5.0
      - image: circleci/postgres:11
        name: psql
        environment:
          POSTGRES_USER: vapor_username
          POSTGRES_DB: vapor_database
          POSTGRES_PASSWORD: vapor_password
    steps:
      - checkout
      - run: swift build
      - run: swift test
  10-linux:
    docker:
      - image: vapor/swift:5.0
      - image: circleci/postgres:10
        name: psql
        environment:
          POSTGRES_USER: vapor_username
          POSTGRES_DB: vapor_database
          POSTGRES_PASSWORD: vapor_password
    steps:
      - checkout
      - run: swift build
      - run: swift test
  9-linux:
    docker:
      - image: vapor/swift:5.0
      - image: circleci/postgres:9
        name: psql
        environment:
          POSTGRES_USER: vapor_username
          POSTGRES_DB: vapor_database
          POSTGRES_PASSWORD: vapor_password
    steps:
      - checkout
      - run: swift build
      - run: swift test
  linux-release:
    docker:
      - image: vapor/swift:5.0
    steps:
      - checkout
      - run: swift build -c release
  linux-performance:
    docker:
      - image: vapor/swift:5.0
      - image: circleci/postgres:9
        name: psql
        environment:
          POSTGRES_USER: vapor_username
          POSTGRES_DB: vapor_database
          POSTGRES_PASSWORD: vapor_password
    steps:
      - checkout
      - run: swift test -c release
workflows:
  version: 2
  tests:
    jobs:
      - 11-linux
      - 10-linux
      - 9-linux
      - linux-release
      - linux-performance
