#if !canImport(ObjectiveC)
import XCTest

extension NIOPostgresTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NIOPostgresTests = [
        ("testAverageLengthNumeric", testAverageLengthNumeric),
        ("testBindInteger", testBindInteger),
        ("testColumnsInJoin", testColumnsInJoin),
        ("testConnectAndClose", testConnectAndClose),
        ("testDates", testDates),
        ("testIntegerArray", testIntegerArray),
        ("testIntegers", testIntegers),
        ("testInvalidPassword", testInvalidPassword),
        ("testMoney", testMoney),
        ("testNumericParsing", testNumericParsing),
        ("testNumericSerialization", testNumericSerialization),
        ("testPerformanceRangeSelectDecodePerformance", testPerformanceRangeSelectDecodePerformance),
        ("testPerformanceSelectHugeModel", testPerformanceSelectHugeModel),
        ("testPerformanceSelectLargeModel", testPerformanceSelectLargeModel),
        ("testPerformanceSelectLargeModelWithLongFieldNames", testPerformanceSelectLargeModelWithLongFieldNames),
        ("testPerformanceSelectMediumModel", testPerformanceSelectMediumModel),
        ("testPerformanceSelectTinyModel", testPerformanceSelectTinyModel),
        ("testPi", testPi),
        ("testQuerySelectParameter", testQuerySelectParameter),
        ("testQueryVersion", testQueryVersion),
        ("testRemoteTLSServer", testRemoteTLSServer),
        ("testSelectType", testSelectType),
        ("testSelectTypes", testSelectTypes),
        ("testSimpleQueryVersion", testSimpleQueryVersion),
        ("testSQLError", testSQLError),
        ("testUUID", testUUID),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(NIOPostgresTests.__allTests__NIOPostgresTests),
    ]
}
#endif
