#if !canImport(ObjectiveC)
import XCTest

extension NIOPostgresTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NIOPostgresTests = [
        ("testAverageLengthNumeric", testAverageLengthNumeric),
        ("testBindInteger", testBindInteger),
        ("testConnectAndClose", testConnectAndClose),
        ("testDates", testDates),
        ("testIntegers", testIntegers),
        ("testInvalidPassword", testInvalidPassword),
        ("testPi", testPi),
        ("testQuerySelectParameter", testQuerySelectParameter),
        ("testQueryVersion", testQueryVersion),
        ("testRangeSelectDecodePerformance", testRangeSelectDecodePerformance),
        ("testRangeSelectPerformance", testRangeSelectPerformance),
        ("testRemoteTLSServer", testRemoteTLSServer),
        ("testSelectPerformance", testSelectPerformance),
        ("testSelectType", testSelectType),
        ("testSelectTypes", testSelectTypes),
        ("testSimpleQueryVersion", testSimpleQueryVersion),
        ("testSQLError", testSQLError),
        ("testUUID", testUUID),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(NIOPostgresTests.__allTests__NIOPostgresTests),
    ]
}
#endif
